name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: description
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Show us what you see!
  - type: dropdown
    id: OS
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows
        - Mac OS
        - Linux
        - Android
        - IOS
        - Other
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Internet Explorer
        - Other
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: additional context
