name: Issue Report
description: File an issue
title: '[Issue]: '
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the issue is about.
      placeholder: description
